#!/usr/bin/env ansible-playbook
---

- name: Configure common packages
  hosts:
    - security_group_webservers
    - security_group_dbservers
  sudo: true
  roles:
    #- ssh-reachable
    - ubuntu-updated
    #- hostname-configured

- name: Configure webserver packages
  hosts: security_group_webservers
  sudo: true
  roles:
    - role: jdauphant.nginx
      nginx_http_params:
        - sendfile "on"
        - access_log "/var/log/nginx/access.log"
      nginx_sites:
        bar:
          - listen 8080
          - location / { try_files $uri $uri/ /index.html; }
          - location /images/ { try_files $uri $uri/ /index.html; }
      nginx_configs:
        proxy:
          - proxy_set_header X-Real-IP  $remote_addr
          - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for

- name: Configure dbserver packages
  hosts: security_group_dbservers
  sudo: true
  roles:
    - { role: ANXS.postgresql }
